name: Tweet new commment/answers on MATLAB Answers (every 2 hours)
# on: [push]
# cron: 
# * * * * * 
# | | | | |
# | | | | |- weekday (0:sun 6: sat)
# | | | |--- month
# | | |----- day
# | |------- hour
# |--------- minute
on:
   schedule:
     - cron: '0 0-23/2 * * *'
#     - cron: '0 0,2,4,6,8,10,12,14,16,18,20,22 * * *'
jobs:
  my-job:
    name: Run tweetNewCommentAnswer.m
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Get Python version
        run: python -V
      - name: Install dependencies (Tweepy)
        run: pip install -r requirements.txt
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: 'R2023a'
      - name: Run script and tweet KR
        uses: matlab-actions/run-command@v1
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET}}
          API_KEY: ${{ secrets.API_KEY}}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET}}  
        with:
          command: tweetNewCommentAnswer
      - name: Run script and tweet DE
        uses: matlab-actions/run-command@v1
        env:
          ACCESS_TOKEN_DE: ${{ secrets.ACCESS_TOKEN_DE}}
          ACCESS_TOKEN_SECRET_DE: ${{ secrets.ACCESS_TOKEN_SECRET_DE}}
          API_KEY_DE: ${{ secrets.API_KEY_DE}}
          API_KEY_SECRET_DE: ${{ secrets.API_KEY_SECRET_DE}}  
        with:
          command: tweetNewCommentAnswer_DE
      - name: Run script and tweet CN
        uses: matlab-actions/run-command@v1
        env:
          ACCESS_TOKEN_CN: ${{ secrets.ACCESS_TOKEN_CN}}
          ACCESS_TOKEN_SECRET_CN: ${{ secrets.ACCESS_TOKEN_SECRET_CN}}
          API_KEY_CN: ${{ secrets.API_KEY_CN}}
          API_KEY_SECRET_CN: ${{ secrets.API_KEY_SECRET_CN}}  
        with:
          command: tweetNewCommentAnswer_CN

